#!/usr/bin/env sh

mkdir -p dist/
pandoc -t revealjs -s presentation/**.md -o dist/index.html -i \
  -V revealjs-url=https://unpkg.com/reveal.js@4.0.2 \
  -V transition=none \
  -V center=false \
  -V width='1920' \
  -V theme=beige \
  --bibliography=bibliography.bib \
  --slide-level=2
