#!/usr/bin/env sh

echo "Building..."

rm -rf public/

mkdir -p public/
cp -r css public/css
cp -r presentation/images public/images
cp -r example public/example

pandoc presentation/**.md\
  -o public/index.html\
  -t revealjs\
  -s\
  --template template/index.html\
  -V highlightjs\
  -V highlightjs-theme:zenburn\
  -V transition=fade\
  -V center=false\
  -V width=1280\
  -V hash=true\
  -L revealjs-codeblock.lua\
  --css css/avenga.css\
  -i\
