#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

$SCRIPTPATH/build
(fswatch --exclude public --recursive . | xargs -n1 $SCRIPTPATH/build & python3 -m http.server -d $SCRIPTPATH/../public)
