name: Build Slides
on: [push]

jobs:
  build:
    name: Pandoc build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: ls
        run: ls
      - name: pwd
        run: pwd
      - uses: docker://pandoc/core:2.9
        with:
          entrypoint: pwd
      - uses: docker://pandoc/core:2.9
        with:
          entrypoint: ./ops/build
          # args: -t revealjs -s ./presentation/slides.md -o ./dist/index.html -i -V transition=none
