name: Build Slides
on: [push]

jobs:
  build:
    name: Pandoc build
    runs-on: ubuntu-18.04
    steps:
      - name: Install pandoc
        run: sudo apt-get install pandoc
      - name: Run build script
        run: ./ops/build
      # - uses: docker://pandoc/core:2.9
      #   with:
      #     entrypoint: /bin/sh
      #   run: ./ops/build
